### ISSUE TITLE
Marcador hiro

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/practica-de-marcador-hiro-team-pc-box#1]
[IMPLEMENTACIÓN DEL MODELO 3D CON MARCADOR HIRO.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-marcador-hiro-team-pc-box/files/8605281/IMPLEMENTACION.DEL.MODELO.3D.CON.MARCADOR.HIRO.pdf)

**Comment by Anthony4523** [comment]
La practica contiene toda la información requerida
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
